name: Sync Epg from Source Repo
 
on:
  push:
  schedule:
    - cron: '15 16,18,20,22,0,2,4,6,8,10,12,14 * * *'
 
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Sync File
        env:
          REPO_URL: https://github.com/sparkssssssssss/epg.git
          REPO_BRANCH: main
          SOURCE_PATH: pp.xml.gz
          DESTINATION_PATH: iptv/epg/e.xml.gz
        run: |
          git clone --quiet $REPO_URL repo-tmp
          cp repo-tmp/$SOURCE_PATH $DESTINATION_PATH
          git add $DESTINATION_PATH
          git commit -m "Sync Epg from Source Repo"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@${{ github.repository }}" HEAD:${{ github.ref }}
