name: EPG Update
on:
  push:
  schedule:
    - cron: '10 16,0,8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update EPG Files
      run: |
        rm -f e.xml e.xml.gz && wget https://raw.githubusercontent.com/sparkssssssssss/epg/main/pp.xml -O e.xml \
        && wget https://raw.githubusercontent.com/sparkssssssssss/epg/main/pp.xml.gz -O e.xml.gz
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add e.xml e.xml.gz
        git commit -m "EPG Automatic Update."
    - name: Push changes
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
