name: epg-sync
 
on:
  push:
    branches: [ main ]
  schedule: 
    - cron: '15 16,18,20,22,0,2,4,6,8,10,12,14 * * *'
 
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Epg Sync
        uses: actions/checkout@v3
 
      - name: Update Epg from Source Repository
        env:
          REPO_URL: https://github.com/sparkssssssssss/epg
          REPO_BRANCH: main
          SOURCE_PATH: sparkssssssssss/epg/pp.xml.gz
          DESTINATION_PATH: iptv/epg/e.xml.gz
        run: |
          git clone --quiet $REPO_URL repo-tmp
          cp repo-tmp/$SOURCE_PATH $DESTINATION_PATH
          git add $DESTINATION_PATH
          git commit -m "Update Epg from Source Repository"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@${{ github.repository }}" HEAD:${{ github.ref }}
        shell: bash
